apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-name
  labels:
    app: service-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-name
  template:
    metadata:
      labels:
        app: service-name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      containers:
        - name: worker
          image: mrsedok/worker-image:latest
          ports:
            - containerPort: 2025
            - containerPort: 3002
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
        - name: bridge
          image: mrsedok/bridge-image:latest
          ports:
            - containerPort: 2024
          env:
            - name: WORKSPACE_ID
              value: "service_name"
            - name: WORKER_HOST
              value: "localhost:3002"
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  type: NodePort
  selector:
    app: service-name
  ports:
    - protocol: TCP
      name: ws
      port: 2024
      targetPort: 2024
    - protocol: TCP
      name: user
      port: 3002
      targetPort: 3002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-name
spec:
  ingressClassName: nginx
  rules:
    - host: service_name.roomcursor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-name
                port:
                  number: 2024
    - host: service_name.roomcursor.com
      http:
        paths:
          - path: /worker
            pathType: Prefix
            backend:
              service:
                name: service-name
                port:
                  number: 3002
